version: "3.8"

services:
  postgres:
    container_name: postgres-pocs
    image: postgres:10.6
    ports:
      - "5432:5432"
    environment:            
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=spring_batch_db
      - TZ=UTC
    # volumes:
    #   - ./postgres/init-schema.sql:/docker-entrypoint-initdb.d/init.sql